/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavegation: typeof import('./src/components/Menu/BottomNavegation.vue')['default']
    Filter: typeof import('./src/components/Filter/Filter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Menu/Sidebar.vue')['default']
  }
}
